### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by eLunate** [ValkyrieRBXL/ValkyrieFramework#12]
Because it's a dotfile, Github doesn't generate the preview for it below the project.

Was it because of the CI that we didn't do it? Could the CI be quickly changed to ignore .md files?

**Comment by Gskartwii** [comment]
It indeed is because of the CI. And yes I probably could make it ignore .md files.

**Comment by eLunate** [comment]
I've updated DirScanner.lua in the CI, you might want to take a look yourself but it should be alright.

**Comment by Gskartwii** [comment]
Resolved.
