### ISSUE TITLE
Core not preserving functions correctly

### ISSUE THREAD

**Issue by Gskartwii** [ValkyrieRBXL/ValkyrieFramework#14]
I have no idea what is going on, but trying to use SOME functions after https://github.com/ValkyrieRBXL/ValkyrieFramework/blob/bleeding-edge/_.mod.lua#L31 causes an "attempt to call a nil value" error even though they were saved in local variables.  
Removing the `setfenv()` calls fixes the problem. That could be done, but it still wouldn't explain what is going on.

**Comment by eLunate** [comment]
We'll just get rid of setfenv because it was an old addition that is no longer required.
4658e7bf177795476089bdc765101c3f98a1ff29
