### ISSUE TITLE
BaseLib:234: table index is nil

### ISSUE THREAD

**Issue by Gskartwii** [ValkyrieRBXL/ValkyrieFramework#17]
``` lua
local Valkyrie = require(workspace.MainModule);
Valkyrie("test", "testKey");
Valkyrie:AddLibrary(function(Wrapper)
	Wrapper:Override"Player":Instance{Kill = function(self) print(self); self.Character:BreakJoints(); end}
end, "Test");
print(getfenv);
Valkyrie:LoadLibrary("Test");
game.Players.LocalPlayer:Kill();
```

Just some simple test code. Output:
```
function: 11B5A670
21:46:36.813 - Workspace.MainModule.Shared.Core.BaseLib:234: table index is nil
21:46:36.813 - Stack Begin
21:46:36.814 - Script 'Workspace.MainModule.Shared.Core.BaseLib', Line 234 - method mod
21:46:36.814 - Script 'Workspace.MainModule.Shared.Core.BaseLib', Line 437 - upvalue newWrapper
21:46:36.815 - Script 'Workspace.MainModule', Line 148 - method LoadLibrary
21:46:36.815 - Script 'Workspace.Script', Line 7
21:46:36.816 - Stack End
```

Also, this was run in Play Solo and a server script.

**Comment by eLunate** [comment]
Odd. Time to take a look.

**Comment by eLunate** [comment]
Okay so I've looked and my copy of _.mod.lua doesn't seem to match up with your stack trace?
*/_.mod.lua* **148:** `wviis[Wrapper(cxitio)] = true`

**Comment by eLunate** [comment]
Okay it should be fixed with the new commit.

**Comment by Gskartwii** [comment]
But now `e.table` is nil.  
I wouldn't like such a solution either. It would break getfenv and the table library.

**Comment by eLunate** [comment]
I do believe that the current solution in BaseLib is based off of misinformation that you gave me yourself. If all environments do happen to share the same identities for the core functions/libraries, then `e` can just become `getfenv(0)` instead of `getfenv(2)`

**Comment by Gskartwii** [comment]
It sure could, but it seems weird to me that `getfenv` is not in `LoadLibrary`'s environment. Also, what misinformation?

**Comment by Gskartwii** [comment]
Weirdly enough, `LoadLibrary`'s environment is completely empty, as seen by `table.foreach(getfenv(1), print)` in `LoadLibrary`. I'm thinking traces of environment nuking.

**Comment by Gskartwii** [comment]
[Yes indeed.](https://github.com/ValkyrieRBXL/ValkyrieFramework/blob/bleeding-edge/_.mod.lua#L192)

**Comment by Gskartwii** [comment]
Okay so it turns out that server-side BaseLib has been completely broken all this time. Like, was it ever tested? I don't recall that happening myself.
```
18:33:04.391 - Workspace.Script:4: Workspace.MainModule:153: attempt to index field 'Glob' (a nil value)
18:33:04.391 - Script 'Workspace.MainModule.Shared.Core.BaseLib', Line 45 - upvalue echoerror
18:33:04.392 - Script 'Workspace.MainModule.Shared.Core.BaseLib', Line 120 - index Override
18:33:04.393 - Script 'Workspace.Script', Line 4
18:33:04.393 - Script 'Workspace.MainModule', Line 169 - method LoadLibrary
18:33:04.393 - Script 'Workspace.Script', Line 7
18:33:04.394 - Stack End
```

**Comment by eLunate** [comment]
It was tested. Are you sure that a commit didn't accidentally break MainModule somewhere? Because if you look, the issue is actually withing MainModule.

Regardless, I've provided a fix.

**Comment by Gskartwii** [comment]
No commits have broken MainModule, unless I'm using git-blame wrong. But yeah, that did the trick, thanks.
