### ISSUE TITLE
BaseLib thinks EnumItems are Instances

### ISSUE THREAD

**Issue by Gskartwii** [ValkyrieRBXL/ValkyrieFramework#28]
Minimal repro, client-side in this case:
```lua
local Valkyrie = _G.ValkyrieC;
Valkyrie:LoadLibrary "Util";

print(Enum.RenderPriority.First.Value); -- .Value to invoke imt.__index
```
Results in the error:
```
13:10:19.751 - Players.Player1.PlayerGui.TetrisManager.GameManager:5: ClassName is not a valid member
13:10:19.751 - Script 'Players.Player1.PlayerScripts.ValkyrieClient.Valkyrie.Core.BaseLib', Line 29 - upvalue echoerror
13:10:19.752 - Script 'Players.Player1.PlayerScripts.ValkyrieClient.Valkyrie.Core.BaseLib', Line 85 - index Value
13:10:19.752 - Script 'Players.Player1.PlayerGui.TetrisManager.GameManager', Line 5
13:10:19.752 - Stack End
```

I don't reference ClassName anywhere in my code, so this error must be coming from BaseLib, which doesn't appear on the stack due to being too smart for Roblox.

The reason this issue occurs is because BaseLib uses a [hacky way](https://github.com/ValkyrieRBXL/ValkyrieFramework/blob/bleeding-edge/Shared/Core/BaseLib.mod.lua#L118) to identify Instances. I just tested this, and apparently `game:GetService(Enum.RenderPriority.First)` does not error but returns `nil` instead. This only applies to `EnumItems` and **not** `Enum.RenderPriority` or `Enum`. I'm pretty sure it has only been doing this since recently.

**Comment by eLunate** [comment]
A possible fix is to pcall game.IsA(Inst, 'Instance) instead and check for true, true
I'll sort that one out now. Shame that it doesn't work.

**Comment by Gskartwii** [comment]
Resolved.
