### ISSUE TITLE
BaseLib has an issue with tables

### ISSUE THREAD

**Issue by Gskartwii** [ValkyrieRBXL/ValkyrieFramework#29]
Minimal reproduction:

```lua
-- LocalScript
local Valkyrie = _G.ValkyrieC;
Valkyrie:LoadLibrary "Util";

local Table = {Number = 0};
local Module = require(script.Module);
Module.Function(Table);
Module.Function(Table);
```
```lua
-- ModuleScript
local Valkyrie = _G.ValkyrieC;
Valkyrie:LoadLibrary "Util";

return {
	Function = function(Table)
		print(Table.Number);
		Table.Number = Table.Number + 1;
		print(Table.Number);
	end
};
```

Output:
```
0
1
0
1
```

**Comment by eLunate** [comment]
Unfortunately an underlying issue in *Lua* wherein the wrapper never gets notified of any changes.
The current system is the better of 2 evils wherein any changes coming into the wrapper are immediately replicated to the other side, as opposed to any changes being pulled in (_Bad bad bad bad bad_)

**Comment by eLunate** [comment]
Has a performance-killing patch. https://github.com/ValkyrieRBXL/ValkyrieFramework/commit/4a548ff1efea29671333c4801fb279889623bf25
